# -*- coding: utf-8 -*-
"""JK_prompt_II_Mod11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/jkowalko/PA11_2/blob/main/JK_prompt_II_Mod11.ipynb

# What drives the price of a car?

![](https://github.com/jkowalko/PA11_2/blob/main/images/kurt.jpeg?raw=1)

**OVERVIEW**

In this application, you will explore a dataset from Kaggle. The original dataset contained information on 3 million used cars. The provided dataset contains information on 426K cars to ensure speed of processing.  Your goal is to understand what factors make a car more or less expensive.  As a result of your analysis, you should provide clear recommendations to your client -- a used car dealership -- as to what consumers value in a used car.

### CRISP-DM Framework

<center>
    <img src = images/crisp.png width = 50%/>
</center>


To frame the task, throughout our practical applications, we will refer back to a standard process in industry for data projects called CRISP-DM.  This process provides a framework for working through a data problem.  Your first step in this application will be to read through a brief overview of CRISP-DM [here](https://mo-pcco.s3.us-east-1.amazonaws.com/BH-PCMLAI/module_11/readings_starter.zip).  After reading the overview, answer the questions below.

### Business Understanding

From a business perspective, we are tasked with identifying key drivers for used car prices.  In the CRISP-DM overview, we are asked to convert this business framing to a data problem definition.  Using a few sentences, reframe the task as a data task with the appropriate technical vocabulary.

I will develop  a prediction model to estimate the used car prices looking at the different features such as mileage, age, make , model, and maybe condition or any other features found in the data set. I will take on a regression analysis to quantify the relationship between certain features selected and the price to try and determine what most influences and a coefficient evaluation. The end state will be a model that predicts prices highlighting key drivers for the dealership ownerships.

### Data Understanding

After considering the business understanding, we want to get familiar with our data.  Write down some steps that you would take to get to know the dataset and identify any quality issues within.  Take time to get to know the dataset and explore what information it contains and how this could be used to inform your business understanding.

Steps to understand the data and obtain a better business understanding

1) Ingest the data and review it
2) Identify any missing values
3) Identify any duplicate values
4) Identify any outliers or wrong types of data
5) Determine what features at first glance might influence cost
6) Correlating at first glance how the features could influence cost
7) Format of data like time or numerical
8) EDA - install Automated EDA to help with understanding data

### Data Preparation

After our initial exploration and fine-tuning of the business understanding, it is time to construct our final dataset prior to modeling.  Here, we want to make sure to handle any integrity issues and cleaning, the engineering of new features, any transformations that we believe should happen (scaling, logarithms, normalization, etc.), and general preparation for modeling with `sklearn`.
"""

import plotly.express as px
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.linear_model import Ridge, LinearRegression, Lasso
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split, GridSearchCV

#Automated EDA
!pip install ydata-profiling

data = pd.read_csv('Data/vehicles.csv')

data.describe()

data.head(10)

data.tail(10)

from ydata_profiling import ProfileReport

profile = ProfileReport(data)
profile.to_file(output_file='output.html')

#Display results of profile
profile

# Check for missing values
print(data.isnull().sum())

#check for duplicate data
data[data.duplicated()]

# Dropping these columns `id`, `region`, `state`, `VIN`, and `size` as they are
#irrelevant to this use case
data = data.drop(['id', 'region', 'state', 'VIN', 'size'], axis=1)

data

# Outlier Price needs to be fixed, too high so will limit to say $100,000.
# Thinking modestly here and assuming not high-end luxury dealership.
data = data[(data['price'] > 0) & (data['price'] <= 100000)]

data.describe()

data.tail()

# limiting odometer to 500,000 miles, anything above that is too old
data = data[(data['odometer'] > 0) & (data['odometer'] <= 500000)]

data.describe()

data.head()

# Remove cars before 1950 , old cars high mileage and since it was capped to
#100K , makes sense to take out
data = data[data['year'] >= 1950]

data.head()

# Missing value, impute on `year` and `odometer` with median
#for outliers
data['year'].fillna(data['year'].median(), inplace=True)
data['odometer'].fillna(data['odometer'].median(), inplace=True)

#Categorical data, let's impute using mode for data consistency or put 'unknown'
for col in ['manufacturer', 'model', 'condition', 'cylinders', 'fuel',
            'transmission', 'drive', 'type', 'paint_color', 'title_status']:
    data[col].fillna(data[col].mode()[0] if data[col].mode().size > 0 else 'unknown', inplace=True)

data.head()

data.tail()

#Checking for unknown values
unknown_values = data[
    (data['manufacturer'] == 'unknown') |
    (data['model'] == 'unknown') |
    (data['condition'] == 'unknown') |
    (data['cylinders'] == 'unknown') |
    (data['fuel'] == 'unknown') |
    (data['transmission'] == 'unknown') |
    (data['drive'] == 'unknown') |
    (data['type'] == 'unknown') |
    (data['paint_color'] == 'unknown') |
    (data['title_status'] == 'unknown')
]

display(unknown_values.head())

# Lets do some feature engineering and create age from year (2025 - year)
data['age'] = 2025 - data['year']

# Let's drop year with age - high correlation
data = data.drop('year', axis=1)

#Dropping model due to high cardinality in y-data profile
data = data.drop('model', axis=1)

# Log tranformation on price and odometer to reduce skewness in data as
# mentioned above
data['log_price'] = np.log1p(data['price'])  # log1p handles zeros
data['log_odometer'] = np.log1p(data['odometer'])

# Let's drop the original price and odometer and implement log trans
#from above
data = data.drop(['price', 'odometer'], axis=1)

# Group uncommond manufactures into "other", just picking 1%
manufacturer_counts = data['manufacturer'].value_counts()
rare_manufacturers = manufacturer_counts[manufacturer_counts / len(data) < 0.01].index
data['manufacturer'] = data['manufacturer'].apply(lambda x: x if x not in rare_manufacturers else 'other')

# Convert categorical variables to dummy variables
categorical_cols = ['manufacturer', 'condition', 'cylinders', 'fuel',
                    'transmission', 'drive', 'type', 'paint_color', 'title_status']
data = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

"""Overview of the Dataset and findings

1) The target varaiable will be price and it's a good format, numeric and will be applied to regression models
2) There are some great features like year, manufacturer, drive, condition that can help determine what drives price of car.
3) Missing Values across cells is 15.8%. There are also some variables with high missing count like cylinders 41.6%, condition 40.8%, drive 30.6%), Paint color 40.5%.
4) Duplicate rows: Calculated using two methods since I didn't feel it was accurate, but it turns out NO Duplicate rows.
5) High Correlations exist which may be dropped but further analysis will need to be done. ex. year , odometer which can be important.

In summary, there are lots of missing data and skewed distributions which will need to be prepared before modeling. The the high correlations will require some transformations so the models can be trained and not overfit.

Creating plots to see if we can find any relationships
"""

# Scatter plot of log_price vs. age (adding color)
plt.figure(figsize=(8, 6))
sns.scatterplot(x='age', y='log_price', data=data, hue='age')
plt.title('Log-Price vs. Car Age', fontsize=14)
plt.xlabel('Car Age (Years)', fontsize=12)
plt.ylabel('Log-Price', fontsize=12)
plt.show()

# Scatter plot of log_price vs. log_odometer
plt.figure(figsize=(8, 6))
sns.scatterplot(x='log_odometer', y='log_price', data=data, hue='log_odometer')
plt.title('Log-Price vs. Log-Odometer', fontsize=14)
plt.xlabel('Log-Odometer (Miles)', fontsize=12)
plt.ylabel('Log-Price', fontsize=12)
plt.show()

# Box plot of log_price by manufacturer
plt.figure(figsize=(10, 6))
sns.boxplot(x='manufacturer_other', y='log_price', data=data, palette='Set2')
plt.title('Log-Price by Manufacturer', fontsize=14)
plt.xlabel('Manufacturer (Other for Rare)', fontsize=12)
plt.ylabel('Log-Price', fontsize=12)
plt.xticks(rotation=45)
plt.show()

"""### Modeling

With your (almost?) final dataset in hand, it is now time to build some models.  Here, you should build a number of different regression models with the price as the target.  In building your models, you should explore different parameters and be sure to cross-validate your findings.

For this part, I'm going to use LinearRegression, Ridge, and Lasso with cross-validation and grid search functions to predict log_price.
"""

# Focusing on features and target price
X = data.drop('log_price', axis=1)
y = data['log_price']

#Spliting data into test and training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Using the Linear Regression model first
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

# Using Ridge Regression and Grid Search function
ridge_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('ridge', Ridge())
])
param_grid = {'ridge__alpha': [0.1, 1.0, 10.0, 100.0]}
grid_ridge = GridSearchCV(ridge_pipeline, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_ridge.fit(X_train, y_train)
y_pred_ridge = grid_ridge.predict(X_test)

# Using Lasso Regression and Grid Search
lasso_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('lasso', Lasso())
])
param_grid = {'lasso__alpha': [0.0001, 0.001, 0.01, 0.1]}
grid_lasso = GridSearchCV(lasso_pipeline, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_lasso.fit(X_train, y_train)
y_pred_lasso = grid_lasso.predict(X_test)

"""### Evaluation

With some modeling accomplished, we aim to reflect on what we identify as a high-quality model and what we are able to learn from this.  We should review our business objective and explore how well we can provide meaningful insight into drivers of used car prices.  Your goal now is to distill your findings and determine whether the earlier phases need revisitation and adjustment or if you have information of value to bring back to your client.
"""

# Evaluating Linear Regression
rmse_lr = mean_squared_error(y_test, y_pred_lr)**0.5
r2_lr = r2_score(y_test, y_pred_lr)
print(f"Eval Linear Regression: {rmse_lr:.4f}, R²: {r2_lr:.4f}")

#Evaluating Ridge Regression
rmse_ridge = mean_squared_error(y_test, y_pred_ridge)**0.5
r2_ridge = r2_score(y_test, y_pred_ridge)
print(f"Eval Ridge Regression: {grid_ridge.best_params_['ridge__alpha']}, RMSE: {rmse_ridge:.4f}, R²: {r2_ridge:.4f}")

#Evaluating Lasso Regression
rmse_lasso = mean_squared_error(y_test, y_pred_lasso)**0.5
r2_lasso = r2_score(y_test, y_pred_lasso)
print(f"Eval Lasso Regression: {grid_lasso.best_params_['lasso__alpha']}, RMSE: {rmse_lasso:.4f}, R²: {r2_lasso:.4f}")

# Going to use Lasso for selection on features, looking at coef's
lasso_best = grid_lasso.best_estimator_.named_steps['lasso']
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': lasso_best.coef_
}).sort_values(by='Coefficient', key=abs, ascending=False)
print("\nTop 5 Features detailed by Lasso Coef:")
print(coef_df.head(5))

"""Coefficient analysis, strongest relationship definition:
1) 6_Cylinders having higher price 0.52
2) 8_Cylinders having 2nd higher price 0.46
3) 4_Cylinders having 3rd higher price 0.32
4) Age being negative -0.31, expected as car is older, price is less
5) Fuel type gas -0.23 , less price also expected compared to say electric

Model Results

*   Linear Regression: Moderate performance but sensitive to multicollinearity (high correlation)

*   Ridge Regression: More stable due to regularization in finding best alpha using grid search

*   Lasso Regression: Best for feature selection and eliminated unimportant features by shrinking their coefficients to zero

Best Performing Model
* Lasso Regression had the lowest RMSE (RMSE: 1.0404) and highest R² (R²: 0.2644), making it the most effective at predicting prices

### Deployment

Now that we've settled on our models and findings, it is time to deliver the information to the client.  You should organize your work as a basic report that details your primary findings.  Keep in mind that your audience is a group of used car dealers interested in fine-tuning their inventory.

*** Key Drivers of Used Car Prices ***
My analysis uncovered several important drivers that impact the price of used cars. Here is the detailed review:

Car Age: Newer vehicles are associated with higher prices. As a car gets older, its value drops as expected. This is shown in both the data analysis and the visual analysis.

Mileage: Cars with lower mileage are more valuable. There's a strong relationship between fewer miles and higher prices.

Manufacturer: Brands like Toyota and Honda, consistently sell for higher prices compared to others. This was evident in both the data summaries and box plots.

Vehicle Types: SUVs and pickups generally sell at higher prices than sedans or compacts. This trend is supported by the model results and visuals.

Condition: Cars labeled as “excellent” or “good” condition typically sell for more money. This was a trending observation.

*** Actionable Insights for Dealerships ****
Key takeaways that can help fine-tune inventory and pricing strategies moving forward.

For Buyers:
Focus on acquiring newer vehicles with lower mileage to inventory. These are in higher demand and can justify higher resale prices. Also, be prepared to pay more for high-demand brands like Toyota, Honda, or a body type like SUVs.

For Sellers:
Marketing a vehicle, I would recommend emphasizing the low mileage, a recent model year, or maybe good condition to attract higher bids.

For Dealerships:
Invest more in popular brands and body types — especially SUVs and pickups.Well-maintained cars are more likely to have better prices as condition adds value. Let data on age, mileage, and brand guide your pricing strategy to stay competitive and profitable.
"""

# Saving the cleaned up dataset
data.to_csv('Data/purified_vehicles.csv', index=False)